# Generated by Django 4.2.30 on 2026-09-09 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='skills',
            name='skill_gained',
            field=models.CharField(default='kosong', max_length=255),
        ),
    ]
