# Generated by Django 4.2.30 on 2026-09-14 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_skills_skill_gained'),
    ]

    operations = [
        migrations.AddField(
            model_name='skills',
            name='skill_level',
            field=models.CharField(choices=[('Beginner', 'beginner'), ('Intermediate', 'intermediate'), ('Advanced', 'advanced'), ('Expert', 'expert')], default='Beginner', max_length=200),
        ),
    ]
