# Generated by Django 4.2.30 on 2026-09-30 04:57

from django.conf import settings
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0005_skills_starred_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('time', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='experience',
            name='starred_by',
            field=models.ManyToManyField(blank=True, related_name='starred_experiences', to=settings.AUTH_USER_MODEL),
        ),
    ]
